name: Commit Stage

on:
  push:
    branches:
      - main

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v3
        with:
          distribution: 'oracle'
          java-version: 17 
      - name: Build
        run: mvn clean package
      - name: Integration Test
        run: mvn integration-test -Pfailsafe

